/**
 * Image SEO Enforcement Service
 * Validates and auto-generates SEO metadata for all images
 * Uses GPT-4o-mini for cost-effective tag generation
 */

import OpenAI from "openai";

// ==================== Types ====================

export interface ImageSeoTags {
  alt: string;
  altHe?: string;
  altAr?: string;
  title: string;
  caption?: string;
  captionHe?: string;
  captionAr?: string;
  keywords: string[];
  filename: string;
  contentLocation?: {
    name: string;
    addressLocality: string;
    addressRegion: string;
    addressCountry: string;
    latitude?: string;
    longitude?: string;
  };
}

export interface ImageSeoInput {
  url: string;
  context?: string; // Article/content context for better AI generation
  contentType?: string; // hotel, attraction, restaurant, etc.
  location?: string; // Dubai Marina, Downtown, etc.
  existingAlt?: string;
  existingTitle?: string;
}

export interface ImageSeoValidation {
  isValid: boolean;
  missingFields: string[];
  warnings: string[];
  score: number;
}

export interface ImageSeoResult {
  validation: ImageSeoValidation;
  tags: ImageSeoTags;
  wasAutoGenerated: boolean;
}

// ==================== Constants ====================

// ALL fields are REQUIRED - image CANNOT be saved without these
const REQUIRED_FIELDS = [
  'alt',
  'title',
  'caption',
  'keywords',
  'contentLocation',
  'altHe',
] as const;

// Dubai areas for location context
const DUBAI_AREAS = [
  'Downtown Dubai', 'Dubai Marina', 'Palm Jumeirah', 'Jumeirah Beach',
  'Business Bay', 'DIFC', 'Al Barsha', 'Deira', 'Bur Dubai', 'JBR',
  'Dubai Creek', 'Al Fahidi', 'Zabeel', 'Dubai Hills', 'Arabian Ranches',
  'City Walk', 'Dubai Mall', 'Mall of the Emirates', 'Global Village',
  'Dubai Frame', 'Museum of the Future', 'Expo City', 'Dubai Silicon Oasis'
];

// ==================== Validation Rules ====================

export const SEO_RULES = {
  alt: {
    minLength: 20,
    maxLength: 125,
    required: true,
    description: 'Alt text must be 20-125 characters, descriptive, not generic',
  },
  altHe: {
    minLength: 10,
    maxLength: 125,
    required: true,
    description: 'Hebrew alt text is required for multilingual SEO',
  },
  title: {
    minLength: 10,
    maxLength: 100,
    required: true,
    description: 'Title must be 10-100 characters, format: "Place - Detail | Brand"',
  },
  caption: {
    minLength: 30,
    maxLength: 200,
    required: true,
    description: 'Caption must be 30-200 characters with useful context',
  },
  filename: {
    pattern: /^[a-z0-9-]+\.(webp|jpg|jpeg|png)$/,
    maxLength: 80,
    required: true,
    description: 'Filename must be lowercase, use hyphens, no underscores/spaces',
  },
  keywords: {
    minCount: 3,
    maxCount: 10,
    required: true,
    description: 'Must include 3-10 relevant keywords',
  },
  contentLocation: {
    required: true,
    description: 'Location data is required for local SEO',
  },
};

// ==================== Validation Functions ====================

/**
 * Validate image SEO completeness
 * ALL FIELDS ARE REQUIRED - no optional fields
 */
export function validateImageSeo(tags: Partial<ImageSeoTags>): ImageSeoValidation {
  const missingFields: string[] = [];
  const warnings: string[] = [];
  let score = 100;

  // ========== ALT TEXT (REQUIRED) ==========
  if (!tags.alt || tags.alt.trim().length === 0) {
    missingFields.push('alt');
    score -= 20;
  } else {
    if (tags.alt.length < SEO_RULES.alt.minLength) {
      missingFields.push(`alt (too short: ${tags.alt.length}/${SEO_RULES.alt.minLength} chars)`);
      score -= 15;
    }
    if (tags.alt.length > SEO_RULES.alt.maxLength) {
      warnings.push(`Alt text too long (${tags.alt.length}/${SEO_RULES.alt.maxLength} chars)`);
      score -= 5;
    }
    // Check for generic alt text
    const genericPatterns = /^(image|photo|picture|pic|img|untitled)(\s+of)?$/i;
    if (genericPatterns.test(tags.alt.trim())) {
      missingFields.push('alt (generic text not allowed)');
      score -= 15;
    }
  }

  // ========== HEBREW ALT TEXT (REQUIRED) ==========
  if (!tags.altHe || tags.altHe.trim().length === 0) {
    missingFields.push('altHe');
    score -= 15;
  } else if (tags.altHe.length < SEO_RULES.altHe.minLength) {
    missingFields.push(`altHe (too short: ${tags.altHe.length}/${SEO_RULES.altHe.minLength} chars)`);
    score -= 10;
  }

  // ========== TITLE (REQUIRED) ==========
  if (!tags.title || tags.title.trim().length === 0) {
    missingFields.push('title');
    score -= 15;
  } else if (tags.title.length < SEO_RULES.title.minLength) {
    missingFields.push(`title (too short: ${tags.title.length}/${SEO_RULES.title.minLength} chars)`);
    score -= 10;
  }

  // ========== CAPTION (REQUIRED) ==========
  if (!tags.caption || tags.caption.trim().length === 0) {
    missingFields.push('caption');
    score -= 10;
  } else if (tags.caption.length < SEO_RULES.caption.minLength) {
    missingFields.push(`caption (too short: ${tags.caption.length}/${SEO_RULES.caption.minLength} chars)`);
    score -= 5;
  }

  // ========== KEYWORDS (REQUIRED) ==========
  if (!tags.keywords || tags.keywords.length === 0) {
    missingFields.push('keywords');
    score -= 10;
  } else if (tags.keywords.length < SEO_RULES.keywords.minCount) {
    missingFields.push(`keywords (need ${SEO_RULES.keywords.minCount}, have ${tags.keywords.length})`);
    score -= 5;
  }

  // ========== CONTENT LOCATION (REQUIRED) ==========
  if (!tags.contentLocation || !tags.contentLocation.name) {
    missingFields.push('contentLocation');
    score -= 10;
  }

  // ========== FILENAME QUALITY (REQUIRED) ==========
  if (tags.filename) {
    const filenamePattern = /^[a-z0-9-]+\.(webp|jpg|jpeg|png)$/;
    if (!filenamePattern.test(tags.filename)) {
      missingFields.push('filename (must be lowercase with hyphens, no underscores)');
      score -= 5;
    }
    const genericFilenamePatterns = /^(img|image|photo|picture|untitled|dsc|img_|photo_|\d+)\.(jpg|jpeg|png|webp|gif)$/i;
    if (genericFilenamePatterns.test(tags.filename)) {
      missingFields.push('filename (generic name not allowed)');
      score -= 5;
    }
  }

  return {
    isValid: missingFields.length === 0,
    missingFields,
    warnings,
    score: Math.max(0, score),
  };
}

// ==================== AI Generation ====================

function getOpenAIClient(): OpenAI | null {
  const apiKey = process.env.AI_INTEGRATIONS_OPENAI_API_KEY || process.env.OPENAI_API_KEY;
  if (!apiKey) return null;
  return new OpenAI({
    apiKey,
    baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL || undefined,
  });
}

/**
 * Generate SEO tags using AI (GPT-4o-mini for cost efficiency)
 */
export async function generateImageSeoTags(input: ImageSeoInput): Promise<ImageSeoTags> {
  const openai = getOpenAIClient();

  if (!openai) {
    // Fallback: generate basic tags from URL/context
    return generateFallbackTags(input);
  }

  const prompt = buildGenerationPrompt(input);

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini", // Cheapest model - ~$0.15/$0.60 per 1M tokens
      messages: [
        {
          role: "system",
          content: `You are an Image SEO specialist for a Dubai travel website (TripMD).
Generate comprehensive SEO metadata for images following these STRICT rules:

ALT TEXT RULES:
- Length: 50-125 characters
- Format: "[Visual description] in [Location], Dubai [optional detail]"
- Include what's shown, not interpretation
- Use natural language, not keywords stuffing
- Example: "Aerial view of Palm Jumeirah artificial island showing crescent shape and hotel buildings in Dubai"

TITLE RULES:
- Length: 30-80 characters
- Format: "[Place/Subject] - [Interesting fact or detail] | TripMD"
- Example: "Burj Khalifa - World's tallest building at 828 meters | TripMD"

CAPTION RULES:
- Length: 50-150 characters
- Informative, adds value beyond alt text
- Can include practical info (opening hours, prices, tips)

FILENAME RULES:
- Lowercase, hyphens only (no underscores/spaces)
- Format: [subject]-[detail]-dubai-[context].webp
- Example: burj-khalifa-observation-deck-sunset-view.webp

KEYWORDS:
- 5-8 relevant keywords
- Include: location, landmark name, activity type, Dubai

Respond ONLY with valid JSON, no markdown or explanation.`
        },
        {
          role: "user",
          content: prompt
        }
      ],
      max_tokens: 1000,
      temperature: 0.3, // Low temperature for consistent output
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      return generateFallbackTags(input);
    }

    // Parse JSON response
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return generateFallbackTags(input);
    }

    const parsed = JSON.parse(jsonMatch[0]);

    return {
      alt: parsed.alt || generateFallbackAlt(input),
      altHe: parsed.altHe || undefined,
      altAr: parsed.altAr || undefined,
      title: parsed.title || generateFallbackTitle(input),
      caption: parsed.caption || undefined,
      captionHe: parsed.captionHe || undefined,
      captionAr: parsed.captionAr || undefined,
      keywords: parsed.keywords || [],
      filename: parsed.filename || generateFallbackFilename(input),
      contentLocation: parsed.contentLocation || detectLocation(input),
    };
  } catch (error) {
    console.error('AI image SEO generation failed:', error);
    return generateFallbackTags(input);
  }
}

function buildGenerationPrompt(input: ImageSeoInput): string {
  let prompt = `Generate SEO metadata for this image:\n\n`;
  prompt += `Image URL: ${input.url}\n`;

  if (input.contentType) {
    prompt += `Content Type: ${input.contentType}\n`;
  }
  if (input.location) {
    prompt += `Location: ${input.location}, Dubai, UAE\n`;
  }
  if (input.context) {
    prompt += `Context: ${input.context}\n`;
  }
  if (input.existingAlt) {
    prompt += `Current Alt (improve this): ${input.existingAlt}\n`;
  }

  prompt += `\nGenerate JSON with: alt, altHe, title, caption, keywords[], filename, contentLocation{}`;

  return prompt;
}

// ==================== Fallback Generation ====================

function generateFallbackTags(input: ImageSeoInput): ImageSeoTags {
  return {
    alt: generateFallbackAlt(input),
    title: generateFallbackTitle(input),
    keywords: generateFallbackKeywords(input),
    filename: generateFallbackFilename(input),
    contentLocation: detectLocation(input),
  };
}

function generateFallbackAlt(input: ImageSeoInput): string {
  const parts: string[] = [];

  if (input.contentType) {
    const typeDescriptions: Record<string, string> = {
      hotel: 'Hotel view',
      attraction: 'Tourist attraction',
      restaurant: 'Restaurant',
      dining: 'Dining experience',
      district: 'District view',
      event: 'Event scene',
      beach: 'Beach view',
    };
    parts.push(typeDescriptions[input.contentType] || 'Scene');
  }

  if (input.location) {
    parts.push(`in ${input.location}`);
  }

  parts.push('Dubai, UAE');

  return parts.join(' ');
}

function generateFallbackTitle(input: ImageSeoInput): string {
  const parts: string[] = [];

  if (input.location) {
    parts.push(input.location);
  } else {
    parts.push('Dubai');
  }

  if (input.contentType) {
    parts.push(`- ${input.contentType.charAt(0).toUpperCase() + input.contentType.slice(1)}`);
  }

  parts.push('| TripMD');

  return parts.join(' ');
}

function generateFallbackFilename(input: ImageSeoInput): string {
  const parts: string[] = [];

  if (input.location) {
    parts.push(input.location.toLowerCase().replace(/\s+/g, '-'));
  }

  if (input.contentType) {
    parts.push(input.contentType.toLowerCase());
  }

  parts.push('dubai');
  parts.push(Date.now().toString(36));

  return parts.join('-') + '.webp';
}

function generateFallbackKeywords(input: ImageSeoInput): string[] {
  const keywords = ['dubai', 'uae', 'travel'];

  if (input.location) {
    keywords.push(input.location.toLowerCase());
  }

  if (input.contentType) {
    keywords.push(input.contentType);

    const relatedKeywords: Record<string, string[]> = {
      hotel: ['accommodation', 'stay', 'resort'],
      attraction: ['tourism', 'sightseeing', 'landmark'],
      restaurant: ['dining', 'food', 'cuisine'],
      beach: ['waterfront', 'coast', 'relaxation'],
    };

    keywords.push(...(relatedKeywords[input.contentType] || []));
  }

  return [...new Set(keywords)];
}

function detectLocation(input: ImageSeoInput): ImageSeoTags['contentLocation'] | undefined {
  // Try to detect Dubai area from input
  const searchText = `${input.url} ${input.context || ''} ${input.location || ''}`.toLowerCase();

  for (const area of DUBAI_AREAS) {
    if (searchText.includes(area.toLowerCase())) {
      return {
        name: area,
        addressLocality: area,
        addressRegion: 'Dubai',
        addressCountry: 'AE',
      };
    }
  }

  if (input.location) {
    return {
      name: input.location,
      addressLocality: input.location,
      addressRegion: 'Dubai',
      addressCountry: 'AE',
    };
  }

  return undefined;
}

// ==================== Main Enforcement Function ====================

/**
 * Enforce SEO tags on an image - validates and auto-generates if needed
 * This is the MAIN function to call before saving any image
 */
export async function enforceImageSeo(
  input: ImageSeoInput,
  existingTags?: Partial<ImageSeoTags>
): Promise<ImageSeoResult> {
  // Step 1: Validate existing tags
  const validation = validateImageSeo(existingTags || {});

  // Step 2: If valid and complete, return as-is
  if (validation.isValid && validation.score >= 80) {
    return {
      validation,
      tags: existingTags as ImageSeoTags,
      wasAutoGenerated: false,
    };
  }

  // Step 3: Generate missing tags using AI
  const generatedTags = await generateImageSeoTags({
    ...input,
    existingAlt: existingTags?.alt,
    existingTitle: existingTags?.title,
  });

  // Step 4: Merge existing with generated (existing takes priority)
  const mergedTags: ImageSeoTags = {
    alt: existingTags?.alt || generatedTags.alt,
    altHe: existingTags?.altHe || generatedTags.altHe,
    altAr: existingTags?.altAr || generatedTags.altAr,
    title: existingTags?.title || generatedTags.title,
    caption: existingTags?.caption || generatedTags.caption,
    captionHe: existingTags?.captionHe || generatedTags.captionHe,
    captionAr: existingTags?.captionAr || generatedTags.captionAr,
    keywords: existingTags?.keywords?.length ? existingTags.keywords : generatedTags.keywords,
    filename: existingTags?.filename || generatedTags.filename,
    contentLocation: existingTags?.contentLocation || generatedTags.contentLocation,
  };

  // Step 5: Re-validate merged tags
  const finalValidation = validateImageSeo(mergedTags);

  return {
    validation: finalValidation,
    tags: mergedTags,
    wasAutoGenerated: true,
  };
}

/**
 * Batch process multiple images
 */
export async function enforceImageSeoBatch(
  images: Array<{ input: ImageSeoInput; existingTags?: Partial<ImageSeoTags> }>
): Promise<ImageSeoResult[]> {
  // Process in parallel with concurrency limit
  const results: ImageSeoResult[] = [];
  const batchSize = 5;

  for (let i = 0; i < images.length; i += batchSize) {
    const batch = images.slice(i, i + batchSize);
    const batchResults = await Promise.all(
      batch.map(({ input, existingTags }) => enforceImageSeo(input, existingTags))
    );
    results.push(...batchResults);
  }

  return results;
}

// ==================== Express Middleware ====================

/**
 * Express middleware to enforce image SEO before saving
 */
export function imageSeoMiddleware() {
  return async (req: any, res: any, next: any) => {
    // Check if request contains image data
    if (!req.body?.image && !req.body?.images && !req.body?.heroImage) {
      return next();
    }

    try {
      // Single image
      if (req.body.image) {
        const result = await enforceImageSeo(
          { url: req.body.image.url || req.body.image },
          req.body.image
        );

        if (!result.validation.isValid) {
          return res.status(400).json({
            error: 'Image SEO validation failed',
            missingFields: result.validation.missingFields,
            warnings: result.validation.warnings,
          });
        }

        req.body.image = { ...req.body.image, ...result.tags };
      }

      // Hero image
      if (req.body.heroImage) {
        const result = await enforceImageSeo(
          {
            url: req.body.heroImage,
            contentType: req.body.contentType,
            context: req.body.title,
          },
          { alt: req.body.heroImageAlt }
        );

        req.body.heroImageAlt = result.tags.alt;
        req.body.heroImageTitle = result.tags.title;
      }

      // Multiple images (gallery)
      if (req.body.images && Array.isArray(req.body.images)) {
        const results = await enforceImageSeoBatch(
          req.body.images.map((img: any) => ({
            input: {
              url: img.image || img.url,
              contentType: req.body.contentType,
              context: req.body.title,
            },
            existingTags: img,
          }))
        );

        req.body.images = req.body.images.map((img: any, i: number) => ({
          ...img,
          ...results[i].tags,
        }));
      }

      next();
    } catch (error) {
      console.error('Image SEO middleware error:', error);
      next(); // Don't block on errors, just continue
    }
  };
}

export default {
  validateImageSeo,
  generateImageSeoTags,
  enforceImageSeo,
  enforceImageSeoBatch,
  imageSeoMiddleware,
  SEO_RULES,
};
